### ISSUE TITLE
Add to NPM registry

### ISSUE THREAD

**Issue by thomgoodman** [WFCD/warframe-relic-data#1]
Can you add this to the NPM registry so that I can use this in my project?

**Comment by Soundofdarkness** [comment]
Considering that I currently don't have an option to run the build system it's extremely old (and probably wrong) data. So I'd rather not put it on npm. If you still need to use it, you can just add it as git dependency for npm. Command should be:
```
npm install soundofdarkness/warframe-relic-data
```
I hope that helps, and sorry for the late response.
