### ISSUE TITLE
:rocket: Add Unique Name to rewards from the relics so we can easily look up related item data

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-relic-data#21]
It'd be nice to have the uniqueName from warframe-items in the titania relic reward data so we can reference those back to the full item data quickly

**Comment by Soundofdarkness** [comment]
Apologies for the late response. If we want to do that, how would we name the property, since uniqueName is already in use for warframes own "id" (or whatever else it could be described as).

**Comment by TobiTenno** [comment]
i don't see why uniqueName couldn't be on relics internal rewards as well

**Comment by Soundofdarkness** [comment]
Oh right, my bad, somehow I thought we already used uniqueId as property, and not uniqueName. We can absolutely do that then.

**Comment by TobiTenno** [comment]
shoot, i mistyped and meant uniqueName 🤦

**Comment by TobiTenno** [comment]
i'm super silly, cause the RewardItem is clearly on there.... :facepalm:

**Comment by Soundofdarkness** [comment]
All perfectly fine ! I didn't properly notice it either ^^
